id: P68A0AB46
initial_creation_type: input
source_metadata:
  title: Chimé Pakmé Nyingtik
  language: en
  description: Texts related to Chimé Pakmé Nyingtik (‘chi med ‘phags ma'i snying
    thig), 'The Heart Essence of the Sublime Lady of Immortality', a longevity practice
    discovered by Jamyang Khyentse Wangpo featuring White Tārā (in the form known
    as Wish-fulfilling Wheel) in union with Avalokiteśvara (in the form known as Lord
    of the Dance).
  volume:
    8731b7b8959f4d2c831864d1b6b46d68:
      title: Introduction to Chimé Pakmé Nyingtik
      parent: Introduction
    c27c88518ff7440f921e3fd6b4a95262:
      title: 'The Sweet Ambrosia of Immortality: Concise Instructions on the Generation
        and Completion Phases of the Single-Form Daily Practice of the Heart Essence
        of the Sublime Lady of Immortality'
      parent: Commentaries
    ef38edaebbec44d29c93457edaed193b:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
    438bbf98cd664e8c95646da9ecc9790f:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    e25937c2c6fb4dd4800efbfbfa794a9d:
      title: Brief Supplementary Text for Intensive Practice (Drupchö) of the Sublime
        Lady of Immortality (Chimé Pakmé Nyingtik)
      parent: Manuals
    18d568363a2c40098f23d02a53f44b23:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    9ae5cc0cd2ac4dff8677420aaa9a3079:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Sādhanas
    5bb50e56f0e74ac3ae56a1f25265a69e:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Sādhanas
created_at: '2022-03-01T03:11:24.459249'
last_modified_at: '2022-03-01T03:11:24.459255'
